using ZipArchives: 
    ZipArchives,
    ZipWriter,
    zip_newfile,
    zip_writefile,
    zip_commitfile,
    zip_abortfile,
    zip_mkdir,
    zip_nentries,
    zip_name,
    zip_names,
    ZipBufferReader,
    zip_openentry,
    zip_readentry,
    zip_findlast_entry,
    zip_iscompressed,
    zip_compressed_size,
    zip_uncompressed_size,
    zip_crc32,
    zip_test_entry,
    zip_isdir,
    zip_name_collision,
    zip_isexecutablefile,
    zip_comment,
    zip_definitely_utf8,
    zip_open_filereader,
    zip_append_archive

using Test: @testset, @test, @test_throws, @test_logs